@startuml
'https://plantuml.com/sequence-diagram

skinparam sequenceMessageAlign center

autonumber

actor User
participant "OpenShift API Server" as API
participant "cert-manager-operator" as Operator

User -> API : Delete istiocsr CR
API -> Operator : Reconcile istiocsr delete event
note over Operator
deletes all resources created
for istio-csr agent installation.
endnote

@enduml
