run:
  timeout: "5m"

linters:
  disable-all: true
  enable: [
    "govet",
    "goimports",
    "gofmt",
    "staticcheck",
    "deadcode",
    "dupl",
    "errcheck",
    "structcheck",
    "unparam",
    "unused",
    "varcheck",
  ]

linters-settings:
  goimports:
    local-prefixes: "github.com/openshift/enhancements/tools"
  govet:
    check-shadowing: false

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
   - linters:
     - staticcheck
     text: "SA1019:"
